### ISSUE TITLE
Need to consider safeguard on math operations. 

### ISSUE THREAD

**Issue by Shalmezad** [Ryan-Amaral/TPG-Python#1]
[Line 126](https://github.com/Ryan-Amaral/PyTPG/blob/master/tpg/learner.py#L126) and [Line 122](https://github.com/Ryan-Amaral/PyTPG/blob/master/tpg/learner.py#L122) in learner.py.
There's no safeguard (that's easily visible) on `log()` or division.

**Comment by Ryan-Amaral** [comment]
Oh yeah, good catch, I'll get on it.
