### ISSUE TITLE
Consider renaming `getNextTeam` to `getNextAgent`

### ISSUE THREAD

**Issue by Shalmezad** [Ryan-Amaral/TPG-Python#4]
https://github.com/Ryan-Amaral/PyTPG/blob/master/tpg/tpg_trainer.py#L102
Since it returns a TpgAgent, may want to call it getNextAgent to make it clearer to whoever uses it that it's an agent instance (thus need to use `agent.reward(task,value)`) instead of a team (would use `team.outcomes[task]=value`).

**Comment by Ryan-Amaral** [comment]
I made it happen, thanks. Just some legacy naming stuff from older code with slightly different structure.
