### ISSUE TITLE
getNextTeam() fails if queue is empty

### ISSUE THREAD

**Issue by Shalmezad** [Ryan-Amaral/TPG-Python#5]
Attempting to call `getNextTeam()` after it's empty throws an error despite the try/finally:
```
  File "/usr/local/lib/python3.6/site-packages/tpg/tpg_trainer.py", line 106, in getNextTeam
    agent = TpgAgent(self.teamQueue.pop(), self)
IndexError: pop from empty list
```

Unfortunately don't know an easy fix for this other than checking `len(self.teamQueue)` (should be fine since the lock is acquired:

**Comment by Ryan-Amaral** [comment]
Maybe it just shows the error because it happened, but execution can continue just fine because it is in a try (don't know haven't tested yet). Though I added this suggestion anyway, thanks.
